option for downloading images
holochain-apps/relay pull request #289
Opened 2024-12-05 11:02 UTC by MasterK0927

It will solve #115 

Added the option for downloading the image.

2024-12-05 19:14 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +      const blob: Blob = new Blob([imageBytes], { type: 'image/png' });
We don't know that the image is a png. Gif and jpg are also supported.

2024-12-05 19:14 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +      link.href = URL.createObjectURL(blob);
The image.dataURL is already a base64 url string, so we don't need to convert it from base64 url string -> blob -> image -> base64 url string. We can just use the original base64 url string.

2024-12-05 19:18 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +  const selectedMessages: Writable<Set<string>> = writable(new Set());
This doesn't need to be a `writable`. In a svelte component we can just use `let var = 'abc'` and svelte will handle the reactivity for you. For example:

```javascript
let myList = []; 

function addItem(newItem) {
   myList = [...myList, newItem]; 
}
```

Now we can just use `myList` in our component and it will update reactively.

2024-12-05 19:19 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +    function toggleMessageSelection(messageHash: string) {
Lets only support selecting a single message at a time for now.

2024-12-05 19:20 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +      icon: 'caretDown',
Please use a "download" icon instead of a "caret" icon. You can get svgs of icons from popular icon packs from [iconify](https://icon-sets.iconify.design/?query=download&search-prefix=ic), and add it to the file `lib/svgIcons.ts`. I believe the ones we are using are mostly from the google material icons set, so that would be the first choice if there is one available.

2024-12-05 19:21 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +  //Function to handle long press
We're using the library [svelte-gestures](https://github.com/Rezi/svelte-gestures) for mobile gesture handling. Please use its included 'on:press` event instead of implementing our own long press logic.

2024-12-05 19:21 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +  //Function to handle long press
Also please select the message with a single click on desktop, and only require long-press for mobile.

2024-12-05 19:24 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +      label: 'Cancel',
If you add any strings to the app that are displayed to the user, please render them with the `sveltekit-i18n` library to ensure we can support multiple languages.

See `lib/translations/en/conversations.json` for the english strings we're using. If you don't see a string there you can add it. Other languages will fallback to english if a translation is not found.

Also if you add a new string please note this in the PR description so we remember to notify volla that we need translations for it.

2024-12-05 19:26 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +      label: 'Copy',
Please change the text of the copy button from "Copy" to "Copy Text" to clarify that it does not copy the image.

2024-12-05 19:34 UTC, mattyg requested changes
Thanks for getting this up so quickly! I've requested some changes. Please let me know if anything is unclear or you want to go over it together on a call.

- Branch Naming: please use a descriptive name for PR branches. I like to follow the convention of prefix the branch name with `feat/`, `fix/`, `chore/`, `doc/`, `build/` similar to conventional commits (https://www.conventionalcommits.org/en/v1.0.0/). At the very least please make the branch name reflect its content. For example, instead of naming this branch `feature`, it could be named something that describes its content such as `feat/download-images`.

- Code Formatting: please install the recommended vscode extensions from `.vscode/extensions.json`. This will ensure that we're both using the same formatter, and the formatter runs when a file is saved so we have consistent formatting throughout the codebase and don't end up with a bunch of formatting diffs in every PR. Let me know if you have any trouble with the setup in vscode (or you use a different editor).

- PR description: in your PR description, please use the text "Resolves #155 Resolves #133" instead of "this will fix #155 #133". Including that exact text will cause github to automatically close the linked issue when the PR is merged.

- Svelte conventions: please go over the [tutorial for svelte v4](https://v4.svelte.dev/) to get comfortable with the best practices / conventions. Svelte provides a lot for you with very simple syntax which makes the code way more readable if you do things its way. So its worth learning and following the "svelte way" of implementing things.

I made a few comments inline, and here are a few more that are easier to list out.

- Image download implementation
	- It doesn't actually seem to download the file for me (on ubuntu 22.04). Lets use [tauri-plugin-dialog](https://v2.tauri.app/plugin/dialog/) for handling file saving cross-platform.
 	
- Message selection
        - Please create a new component MessageActions to encapsulate the logic and rendering of the message action buttons. It can take the Message as an input prop.
	- Clicking outside the selected message should deselect it.
	- The buttons should be styled similarly to other buttons in the app (see the colors used in the button in `routes/account/+page.svelte`)
	- If a message contains both images and text, then we should still have a copy button for copying the text.

2024-12-06 03:42 UTC, MasterK0927 commented on ui/src/routes/conversations/[id]/+page.svelte
> +      link.href = URL.createObjectURL(blob);
I tried it without the base64tobytes conversion, but it was downloading a corrupted image. 

For viewing the downloaded image, we have to check **Donwload** folder. 

Anyway we have to replace it with plugin.

2024-12-07 07:45 UTC, MasterK0927 commented
This pull request has been migrated to #292  , please refer to the new pull request for further changes.

2024-12-07 07:45 UTC, closed without merging