added success and error toasts
holochain-apps/relay pull request #295
Opened 2024-12-10 09:12 UTC by MasterK0927

Resolves #115 

- Adds success toasts for Copy actions ("Copied to clipboard").
-  Adds error toasts for Copy actions (if copyToClipboard action fails).
- Adds error toast for FirstName update in profile (if its less than 3 characters).
- Adds error toast for profile update (if updateName action fails).

**Strings Added:** Added new strings in the common.json.
- [`Line 32`](https://github.com/holochain-apps/volla-messages/blob/42247b0798be479a1c37c439d0f2676ede5fbd9e/ui/src/lib/translations/en/common.json#L32)
- [`Line 33`](https://github.com/holochain-apps/volla-messages/blob/42247b0798be479a1c37c439d0f2676ede5fbd9e/ui/src/lib/translations/en/common.json#L33)
- [`Line 34`](https://github.com/holochain-apps/volla-messages/blob/42247b0798be479a1c37c439d0f2676ede5fbd9e/ui/src/lib/translations/en/common.json#L34)
- [`Line 35`](https://github.com/holochain-apps/volla-messages/blob/42247b0798be479a1c37c439d0f2676ede5fbd9e/ui/src/lib/translations/en/common.json#L35)

2024-12-10 17:34 UTC, mattyg commented on ui/src/lib/translations/en/common.json
> +  "copy_code_success": "Copied to clipboard",
```suggestion
  "copy_success": "Copied to clipboard",
```

2024-12-10 17:34 UTC, mattyg commented on ui/src/lib/translations/en/common.json
> +  "copy_code_error": "Failed to copy"
```suggestion
  "copy_error": "Failed to copy"
```

2024-12-10 17:36 UTC, mattyg commented on ui/src/lib/translations/en/common.json
> +  "first_name_update_error": "First name must be at least 3 characters long",
I think this should be prevented by disabling the submit button when the first name is < 3 characters, right?

2024-12-10 17:38 UTC, MasterK0927 commented on ui/src/lib/translations/en/common.json
> +  "first_name_update_error": "First name must be at least 3 characters long",
In edit profile section, there is just one tick and cross button. Not the actual  submit button

2024-12-10 17:41 UTC, mattyg commented on ui/src/routes/account/+page.svelte
> +<Toaster position="bottom-end" />
We already have the Toaster component rendered on the root layout in src/routes/+layout.svelte -- all pages are rendered in a slot within this layout.

2024-12-10 17:42 UTC, mattyg commented on ui/src/routes/contacts/ContactEditor.svelte
> +                copyToClipboard(contact.publicKeyB64);
copyToClipboard is returning a Promise, so we should await its resolution before displaying an error / success notice.

2024-12-10 17:43 UTC, mattyg commented on ui/src/lib/translations/en/common.json
> +  "first_name_update_error": "First name must be at least 3 characters long",
Yes I mean the "tick" button

2024-12-10 17:49 UTC, mattyg commented on ui/src/routes/account/+page.svelte
> +        toast.error(`${$t("common.copy_contact_code_error")}: ${e.message}`);
This translation string key doesn't exist.

2024-12-10 17:52 UTC, MasterK0927 commented on ui/src/routes/account/+page.svelte
> +        toast.error(`${$t("common.copy_contact_code_error")}: ${e.message}`);
Sorry for the mislook, forgotten to remove it after I decided to have a common copy message.

2024-12-10 17:53 UTC, mattyg requested changes
Thanks - requested a few changes inline. 

Please make future PRs against the `develop` branch and label them with "should-backport-0.3". Then after they are merged, make another PR to backport them to `develop-0.3` branch. We can leave this one as is.

I believe there are more places in the app where we want to display notices to the user. Off the top of my head I think we're missing:
- share contact code error
- image upload error
- joining conversation error
- creating conversation error
- camera permissions error
- scan qr code error

Can you please review the app and make a list of all the other places we may want to display error / success notices because no other feedback is provided via the normal UI? Then please update the issue to list them so we're sure we implemented them all.

2024-12-10 17:58 UTC, MasterK0927 commented
> Thanks - requested a few changes inline. 
> 
> Please make future PRs against the `develop` branch and label them with "should-backport-0.3". Then after they are merged, make another PR to backport them to `develop-0.3` branch. We can leave this one as is.
> 
> I believe there are more places in the app where we want to display notices to the user. Off the top of my head I think we're missing:
> - share contact code error
> - image upload error
> - joining conversation error
> - creating conversation error
> - camera permissions error
> - scan qr code error
> 
> Can you please review the app and make a list of all the other places we may want to display error / success notices because no other feedback is provided via the normal UI? Then please update the issue to list them so we're sure we implemented them all.


Had gone through the flow once, figured out some areas we need to handle errors and where it is handled correctly. Will list them out.

2024-12-11 11:22 UTC, MasterK0927 commented
Connection & Setup
----------------
* [ ] Name entry validation (min 3 chars) validated using Next button disabled for < 3 chars
* [ ] Avatar selection feedback on upload by showing uploaded image 
* [ ] Avatar selection image upload failure error toast
* [ ] Holochain conductor failure error toast
* [ ] CreateAccount failure error tost

Account Management
----------------
* [ ] Avatar selection feedback on upload by showing uploaded image 
* [ ] Avatar selection image upload failure error toast
* [ ] Name editing - Save button disabled for < 3 chars
* [ ] Copy contact code success message
* [ ] Copy contact code error message
* [ ] QR code scan failure error toast
* [ ] QR code scan permission failure error toast

Join Conversation
----------------
* [ ] Page has on screen error handling for invalid code (no toast needed)
* Join conversation failure error needs classification:
   * [ ] Duplicate contact errors
   * [ ] General errors

New Contact/Group
----------------
* [ ] Page has on screen error handling for invalid code (no toast needed)
* [ ] Avatar selection feedback on upload by showing uploaded image 
* [ ] CreateConversation failure error toast

Chat Screens
-----------
* [ ] Pending confirmation - Copy invite success and failure toast
* [ ] Group view - Copy invite success and failure toast
* [ ] Contact view - Copy invite success and failure toast

Group Management
--------------
* [ ] AddContactsToConversation failure error toast

2024-12-11 11:29 UTC, MasterK0927 commented on ui/src/lib/translations/en/common.json
> +  "copy_code_success": "Copied to clipboard",
added the same in new commit

2024-12-11 11:30 UTC, MasterK0927 commented on ui/src/lib/translations/en/common.json
> +  "copy_code_error": "Failed to copy"
added the same in new commit

2024-12-11 18:16 UTC, mattyg commented on ui/src/lib/translations/en/common.json
> +  "scan_error": "Failed to scan the QR code. Please try again.",
```suggestion
  "scan_error": "Failed to scan the QR code.",
```

2024-12-11 18:18 UTC, mattyg commented on ui/src/lib/translations/en/common.json
> +  "upload_image_error": "Error uploading the image",
```suggestion
  "upload_image_error": "Failed to upload image",
```

2024-12-11 18:19 UTC, mattyg commented on ui/src/lib/translations/en/common.json
> +  "update_profile_error": "Failed to update the profile.",
```suggestion
  "update_profile_error": "Failed to update the profile",
```

2024-12-11 18:19 UTC, mattyg commented on ui/src/lib/translations/en/common.json
> +  "copy_error": "Failed to copy",
```suggestion
  "copy_error": "Failed to copy to clipboard",
```

2024-12-11 18:21 UTC, mattyg commented on ui/src/lib/translations/en/common.json
> +  "share_text_error": "Failed to share code",
```suggestion
  "share_text_error": "Failed to share code",
```

Lets either make this `share_code_error`, or change the text to be "Failed to share text"

2024-12-11 18:25 UTC, mattyg commented on ui/src/routes/conversations/[id]/invite/+page.svelte
> +    try{
```suggestion
    try {
```

2024-12-11 18:26 UTC, mattyg commented on ui/src/lib/translations/en/common.json
> +  "add_to_conversation_error": "Failed to add to conversation"
```suggestion
  "add_contact_to_conversation_error": "Failed to add contact to conversation"
```

2024-12-11 18:26 UTC, mattyg commented on ui/src/routes/conversations/[id]/invite/+page.svelte
> +      toast.error(`${$t("common.add_to_conversation_error")}: ${e.message}`);
```suggestion
      toast.error(`${$t("common.add_contact_to_conversation_error")}: ${e.message}`);
```

2024-12-11 18:36 UTC, mattyg commented on ui/src/routes/account/+page.svelte
> +        disabled={firstName.trim().length < MIN_FIRST_NAME_LENGTH}
Since this is now checked in a few places in this component, maybe this is a good time to replace them with a single derived value:

```
$: isFirstNameValid = firstName.trim().length >= MIN_FIRST_NAME_LENGTH;
```

2024-12-11 18:37 UTC, mattyg requested changes
This looks great! Just some minor changes requested.

I think when we merge this PR we should create a ticket for all the new translations needed to easily communicate that.

2024-12-11 21:08 UTC, mattyg approved these changes

2024-12-11 21:08 UTC, merged

2024-12-11 21:09 UTC, mattyg commented
Okay @MasterK0927 I merged this into `develop-0.3` -- now you'll have to forward port it to `develop`. Are you comfortable doing that or you do want to go over it together?

2024-12-11 21:12 UTC, MasterK0927 commented
> Okay @MasterK0927 I merged this into `develop-0.3` -- now you'll have to forward port it to `develop`. Are you comfortable doing that or you do want to go over it together?

If possible, one demo will help me to adapt with it. So going over it together will be good for me.

2024-12-11 21:24 UTC, mattyg commented on ui/src/routes/account/+page.svelte
> +        disabled={isFirstNameValid}
ah crap I missed this earlier -- this should be `disabled={!isFirstNameValid}`

2024-12-11 21:25 UTC, mattyg commented on ui/src/routes/register/+page.svelte
> +    <Button on:click={saveName} disabled={isFirstNameValid}>
same here