Adds file sharing functionality and fixes many known bugs
holochain-apps/relay pull request #318
Opened 2024-12-16 08:50 UTC by MasterK0927

Resolves #124  
Resolves #317 

1. Allows user to share any kind of file.
2. Currently limits them to 15Mb uploads at max (creating separate issue for it).
3. Thumbnail for pdf and image files, fallback icons for others.
4. Fixes the color mismatch issue reported in #317 
5. Adds an option to cancel or deselect selected files before sending (see image attached for reference). 

Strings added to common.json
`large_file_error`

![Screenshot_2024-12-16-15-06-40-110_com.volla.messages-edit.jpg](https://github.com/user-attachments/assets/8da2d0fb-7dea-4e07-86c8-5b82c7367c2c)

2024-12-16 19:08 UTC, mattyg commented on dnas/relay/zomes/integrity/relay/src/message.rs
> +    pub files: Vec<File>,
Ahh, I didn't realize this is what you were referring to in your question. 

So because this changes the code of an integrity zome, it also changes the DNA hash of the `relay` DNA, and thus is a network breaking-change. This means that users on a prior version of the app will not be in the same network as users on this version.

I agree the naming here is not accurate, so I do want to change it, but we'll need to be careful about how its done.

I suggest the following:
- Modify this PR to be only the *non-breaking* changes necessary to implement this feature (i.e. all 
- This PR gets merged into `develop` and backported to `develop-0.3`
- Open another PR with the *breaking* changes
- The breaking PR gets merged into `develop` -- **but does not get backported to `develop-0.3`**

Thus when we are ready to update the app to 0.4, which is itself a network breaking change, we will also include this breaking change as well.

While I would generally prefer consistent naming in the front-end and back-end, I see that it probably makes sense to make an exception here to avoid the breaking change. But also, lets keep the scope of differences between `develop` and `develop-0.3` as minimal as possible (i.e. lets use the new naming "files" in the front-end, except when making requests to the backend).

2024-12-16 19:10 UTC, mattyg commented on package.json
> +    "pdfjs-dist": "^4.8.69",
I think this is a nice idea, but was not a requirement to resolve the issue. 

In the future, I would recommend making an issue for it so it can be prioritized against others. If we are going to support PDF previews, then I would want to support other file type previews as well, with a unified implementation as much as possible.

For now I would suggest removing this functionality from this PR and opening a separate PR with it, so we don't loose track of the work.

2024-12-16 19:12 UTC, mattyg commented on ui/src/lib/PDFThumbnail.svelte
I'll avoid commenting on this, and we'll do it in a separate PR with just this PDF thumbnail feature, if that's okay with you.

2024-12-16 19:20 UTC, mattyg commented on ui/src/lib/svgIcons.ts
> +  audio:
This is specifically for `mp3` not audio

2024-12-16 19:20 UTC, mattyg commented on ui/src/lib/svgIcons.ts
> +  video:
This is specifically for mp4 files, not all videos.

2024-12-16 19:26 UTC, mattyg commented on ui/src/lib/svgIcons.ts
A few comments on these icons.

We should have consistent styling of all file icons, rather than taking icons with specific file extensions from different icon packs. To accomplish this I think we have 2 different options:
- Option 1: We support a couple very-common file type icons, while all others fall back to a generic file icon. The common file type icons are *not* specific to a file extension, but rather a type of file. I.e. we have icons for document, audio, video, and a fallback generic file icon.
- Option 2: We create a component to render a generic file icon, with any arbitrary file extension text inside of it. Then when rendering the component we specify the file extension text.

Either option is okay with me, I don't feel strongly. You could ask for feedback if you don't either.

2024-12-16 19:29 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +                id: crypto.randomUUID(),
I don't understand the purpose of this.

2024-12-16 19:30 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +  function formatFileSize(size: number): string {
Please find a well-maintained js library to provide this utility for us.

2024-12-16 19:30 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +  function formatFileName(file: FileMetadata, maxCharacters: number = 10): string {
I don't understand the purpose of this. Why does the file name need to be altered?

2024-12-16 19:31 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +  function formatFileIcon(file: FileMetadata): string {
This will be altered by the changes to icons from the previous comment.

2024-12-16 19:31 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +                  : ''} "
```suggestion
                  : ''}"
```

2024-12-16 19:32 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +                              {#if file.fileType.startsWith("image/")}
:+1:

2024-12-16 19:32 UTC, MasterK0927 commented on ui/src/routes/conversations/[id]/+page.svelte
> +  function formatFileName(file: FileMetadata, maxCharacters: number = 10): string {
Please see the reference image, we can show a limited text in the text area. So if file name is too big, we can truncate it.

2024-12-16 19:32 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +                              {:else if file.fileType === "application/pdf"}
This will be pulled out temporarily to review in a separate PR

2024-12-16 19:34 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +            {:else if file.dataURL && file.fileType.startsWith("application/pdf")}
This will be pulled out temporarily to review in a separate PR, if thats okay

2024-12-16 19:34 UTC, MasterK0927 commented on ui/src/routes/conversations/[id]/+page.svelte
> +                id: crypto.randomUUID(),
It's used for deselecting the files we want to send.

2024-12-16 19:34 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +    return "file";
:+1:

2024-12-16 19:35 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +    //Final fallback
```suggestion
    // Final fallback
```

2024-12-16 19:35 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +    //Extension based fallback
```suggestion
    // Extension based fallback
```

2024-12-16 19:43 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +  //To get the icon name based on the file type
```suggestion
  // To get the icon name based on the file type
```

2024-12-16 19:46 UTC, MasterK0927 commented on package.json
> +    "pdfjs-dist": "^4.8.69",
Actually Dr Wurzer wanted to have thumbnail for pdfs, so I added it.

2024-12-16 19:48 UTC, mattyg commented on ui/src/lib/translations/en/common.json
> +  "large_file_error": "Currently we don't support files larger than {{maxSize}}"
```suggestion
  "large_file_error": "Attached files are limited to {{maxSize}}"
```

2024-12-16 19:52 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +  function formatFileName(file: FileMetadata, maxCharacters: number = 10): string {
I would suggest we simplify this significantly:

- Option 1: slice the string to a maximum characters, then append "..." 
- Option 2: render the full string, but use the css property `text-overflow: ellipsis;`

2024-12-16 19:57 UTC, MasterK0927 commented on ui/src/routes/conversations/[id]/+page.svelte
> +  function formatFileName(file: FileMetadata, maxCharacters: number = 10): string {
Current impl allows us to specify the maxLength we want, so that we can use it in, multiple usecases. And it aligns with the first option.

2024-12-16 20:03 UTC, mattyg requested changes
Very nice! Made some comments inline.

- Can you please make a ticket "Translations Needed" with a checklist of all the translations we need from the recent 3 PRs? 

- Files displayed in chat should align to the right of the page, and not be streched to the length of images below
![image](https://github.com/user-attachments/assets/7b83bed1-9a88-4da8-92b2-a3a7c6b8d069)

- If I attach a file, then remove it, then attach the same file again, it is not added to the message.

- If I attach a file, then remove it, then click the attach button again, the previous file is selected by default. I think no files should be selected.

2024-12-16 20:04 UTC, mattyg commented on package.json
> +    "pdfjs-dist": "^4.8.69",
Ah okay. Then we'll keep it in this PR and I'll update my comments.

2024-12-16 20:09 UTC, mattyg commented on ui/src/lib/PDFThumbnail.svelte
> +      pdfjsLib.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/4.8.69/pdf.worker.min.mjs`;
I'm not sure about these, but I might be missing something:
- why does import happen when mounting the component?
- why is the import async?
- why are we pulling from a CDN rather than bundling the dependency?

2024-12-16 20:12 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +                id: crypto.randomUUID(),
We should be able to just use the index of the file in the list, right?

2024-12-16 20:14 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +  function formatFileName(file: FileMetadata, maxCharacters: number = 10): string {
I think the implementation is overly complex which will make it harder to read and maintain. Please distill it down to just what I outlined above.

2024-12-16 20:15 UTC, mattyg commented on package.json
> +    "pdfjs-dist": "^4.8.69",
Next time, if there are additional requirements, please make an issue for them or add them to the existing issue.

2024-12-16 20:20 UTC, mattyg commented on ui/src/lib/PDFThumbnail.svelte
> +  <SvgIcon icon={fallbackIcon} color={$modeCurrent ? "black" : "white"} size={width.toString()} />
:+1:

2024-12-16 20:23 UTC, mattyg commented
Additional comments related to PDF generation:

- When I attach a PDF, I do not see a preview, and get the following error in console (on ubuntu 22.04)
![image](https://github.com/user-attachments/assets/4027fc96-52f8-4abf-9dc1-2c56760b7e1b). It does fall back to the pdf icon which is great.

2024-12-17 00:20 UTC, mattyg commented
Also please update the description to say:

Resolves #124
Resolves #137 

(currently only the first ticket will be automatically closed when the PR is merged. github isn't that smart :) )

2024-12-18 09:41 UTC, MasterK0927 commented on ui/src/routes/conversations/[id]/+page.svelte
> +                id: crypto.randomUUID(),
I tried with index first, but with the similar files there was issues, so I chose id as the parameter.

2024-12-18 10:10 UTC, MasterK0927 commented on ui/src/lib/PDFThumbnail.svelte
> +      pdfjsLib.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/4.8.69/pdf.worker.min.mjs`;
- Import is happening during component mounting for achieving lazy loading, to reduce the initial bundle size by loading `pdfjs-dist` only when the component is needed.

- I’ve faced import-related issues with `pdfjs-dist` in previous projects as well. While using it with React/Next.js, I encountered the same problem, and it wasn’t resolved for me either (refer to [this](https://github.com/vercel/next.js/issues/58313) thread). I ended up migrating to `react-pdf`. There’s something similar to it, like `svelte-pdf`, but it’s not maintained. So I switched to cdn approach.

2024-12-18 12:26 UTC, MasterK0927 commented
Made all then changes according to the comments.

2024-12-21 17:06 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +      archivefile: ["zip", "rar", "7z", "tar", "gz"],
Just a note that it might be simpler to match based on mime type rather than file extension (as mime types for video are mostly `video/*`, etc.). But this is fine.

2024-12-21 17:07 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +    return fileName.slice(0, maxLength) + "...";
:+1:

2024-12-21 18:20 UTC, mattyg commented on ui/src/lib/PDFThumbnail.svelte
> +      pdfjsLib.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/4.8.69/pdf.worker.min.mjs`;
> Import is happening during component mounting for achieving lazy loading, to reduce the initial bundle size by loading pdfjs-dist only when the component is needed.

I wouldn't worry about initial bundle size. Since this is a desktop/mobile app, the user already has the initial bundle locally and just renders it, so its not the big performance hit like on the web where the user has to fetch the initial bundle before they can render anything.

> I’ve faced import-related issues with pdfjs-dist in previous projects as well. While using it with React/Next.js, I encountered the same problem, and it wasn’t resolved for me either (refer to https://github.com/vercel/next.js/issues/58313 thread). I ended up migrating to react-pdf. There’s something similar to it, like svelte-pdf, but it’s not maintained. So I switched to cdn approach.

I dug into some github issue threads on the pdfjs repo and was able to get it working with the local worker included in the the npm package. I pushed the change to this branch. Please take a look at how it was implemented.

2024-12-21 18:23 UTC, mattyg requested changes
Looking good - almost there!

- The fallback pdf icon is larger than the others
![image](https://github.com/user-attachments/assets/98ae2602-23fc-49b9-ace1-50942f170583)
- The fallback file icon looks like a different design than the others (it has a triangle on the top right corner). Can we get the designs to be consistent?
- When I attach a file, then press the enter key, the file is removed from the message.
- There's a bunch of merge conflicts that need to be resolved before I can merge this.

2024-12-23 20:16 UTC, mattyg commented
> The fallback pdf icon is larger than the others

This has not been addressed. See the screenshot below. The pdf fallback icon is noticeably larger than the other file type icons.

> There's a bunch of merge conflicts that need to be resolved before we can merge this

This still needs to be addressed before I can merge.

2024-12-23 20:17 UTC, mattyg requested changes
> The fallback pdf icon is larger than the others

This still needs to be addressed. See the screenshot below -- the pdf fallback icon is noticeably larger than the other file type icons.
![image](https://github.com/user-attachments/assets/53f6926f-bb71-47a1-95f6-8d96f3e58266)


> There's a bunch of merge conflicts that need to be resolved before we can merge this

This still needs to be addressed before I can merge.

2024-12-24 07:44 UTC, MasterK0927 commented
> > The fallback pdf icon is larger than the others
> 
> This still needs to be addressed. See the screenshot below -- the pdf fallback icon is noticeably larger than the other file type icons. ![image](https://private-user-images.githubusercontent.com/159270/398250132-53f6926f-bb71-47a1-95f6-8d96f3e58266.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjQwODcsIm5iZiI6MTczNTAyMzc4NywicGF0aCI6Ii8xNTkyNzAvMzk4MjUwMTMyLTUzZjY5MjZmLWJiNzEtNDdhMS05NWY2LThkOTZmM2U1ODI2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQwNzAzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZmFkZGM2ODAzMTQyMzY4ODYyMjg2OWM2YjdlYzFhNDBkOGQ5MDBmMjFiZjNiOGJiZjI3YzllMGY3YmQ1MWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.j7LndRf2huRl0Pdz06NO8wyEWXws0UwmJRhJgqdP9MU)
> 
> > There's a bunch of merge conflicts that need to be resolved before we can merge this
> 
> This still needs to be addressed before I can merge.

I reviewed the merge conflicts, and they involve breaking changes. Some files have been completely modified, while certain parts have been migrated to new components. What's the best way to handle them?

2024-12-24 08:01 UTC, MasterK0927 commented
> > The fallback pdf icon is larger than the others
> 
> This still needs to be addressed. See the screenshot below -- the pdf fallback icon is noticeably larger than the other file type icons. ![image](https://private-user-images.githubusercontent.com/159270/398250132-53f6926f-bb71-47a1-95f6-8d96f3e58266.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjczNjUsIm5iZiI6MTczNTAyNzA2NSwicGF0aCI6Ii8xNTkyNzAvMzk4MjUwMTMyLTUzZjY5MjZmLWJiNzEtNDdhMS05NWY2LThkOTZmM2U1ODI2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQwNzU3NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWU1N2YyNTQ5MzFkYTliNjNhMGZhOWE2NmE4NmZmYjZkOWNjY2U5Njg5M2JiNmQ2NTk1Yzc4ODJlN2FkYzAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ISQgcES2ZW5bZ8xwhEn2UW_5DGm01dsyFsZG5zqcCcw)
> 
> > There's a bunch of merge conflicts that need to be resolved before we can merge this
> 
> This still needs to be addressed before I can merge.

@mattyg For me its working fine, can you please check it once again doing a git pull ?
![Screenshot from 2024-12-24 13-29-41](https://github.com/user-attachments/assets/8f3241b0-e312-4bee-9b68-c43ffe65bb16)

2024-12-24 13:49 UTC, mattyg requested changes
> @mattyg For me its working fine, can you please check it once again doing a git pull ?
- Whoops my bad, it looks good to me too. Sorry about that.

Sorry just another 2 minor changes I just noticed:
- In the message input, the pdf icon is a different height (it looks like the pdf icon is the proper height, but the other icons should be taller)
![image](https://github.com/user-attachments/assets/8dcab616-668c-4659-a0c6-75f97d1caec6)

- When I receive messages with files from other users (i.e. when the message is displayed on on the left side of the page), the file icon should be on the left side of the file title & size.

- Sorry there are so many merge conflicts. I've done a lot of refactoring over the past week and will be doing more this week. I'm guessing it might be easiest to make a new branch off develop and copy the relevant changes into it.

2024-12-26 21:25 UTC, MasterK0927 commented
This has been moved to #369

2024-12-26 21:25 UTC, closed without merging