feat: file sharing and upload cancelling
holochain-apps/relay pull request #369
Opened 2024-12-26 21:23 UTC by MasterK0927

Synced version of #318 

Resolves https://github.com/holochain-apps/volla-messages/issues/124
Resolves https://github.com/holochain-apps/volla-messages/issues/317

- Allows user to share any kind of file.
- Currently limits them to 15Mb uploads at max (creating separate issue for it).
- Thumbnail for pdf and image files, fallback icons for others.
- Fixes the color mismatch issue reported in https://github.com/holochain-apps/volla-messages/issues/317
- Adds an option to cancel or deselect selected files before sending.
- Strings added to common.json
    `large_file_error`

2024-12-26 21:30 UTC, mattyg commented on package.json
> +  }
None of these belong in the root package.json. They are all used only in the `ui` workspace, so they belong in the `ui/package.json`

2024-12-26 21:35 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +  }
For clearer organization, please extract these functions into a standalone component `FileIcon` which will handle rendering the icon for a given File.

Then the `FileIcon` component can be used in both `ConversationMessages` and `ConversationMessagesInput`

2024-12-26 21:37 UTC, mattyg commented on ui/src/routes/conversations/[id]/ConversationMessageInput.svelte
> +  const MAX_FILE_SIZE = 15 * 1024 * 1024; // 15MB
This is an app-level config, so should be moved to `ui/src/config.ts`

2024-12-26 21:39 UTC, mattyg commented on ui/src/translations/en/common.json
> +  "large_file_error": "Attached files are limited to {{maxSize}}"
These messages would only be rendered in the `/conversations` routes, right? If so, they belong in the `translations/en/conversations.json`

2024-12-26 21:40 UTC, mattyg commented on ui/vite.config.ts
> +  },
I don't think these custom vite config is necessary, unless I'm missing something.

2024-12-26 21:41 UTC, mattyg requested changes
- I requested a bunch of changes in comments inline
- I'm not able to run `npm i`, there appear to be conflicting dependencies )I'm not able to review the PR further due to this issue)

2024-12-27 15:10 UTC, mattyg commented on ui/src/routes/conversations/[id]/Message.svelte
> +  import FileIcon from "../../../lib/FileIcon.svelte";
```suggestion
  import FileIcon from "$lib/FileIcon.svelte";
```

2024-12-27 15:14 UTC, mattyg commented on ui/src/lib/FileIcon.svelte
> +  import type { Image } from "../types";
```suggestion
  import type { Image } from "$lib/types";
```

2024-12-27 15:21 UTC, mattyg commented on ui/src/routes/conversations/[id]/+page.svelte
> +        <ConversationMessages messages={$processedMessages} {formatFileName} />
I think we should be able to push this `formatFileName` function down into the FileIcon component as well (or if we want to keep the file icon separate, maybe a `FileIconNamed` component that includes it). 

Currently we're duplicating the rendering of file name, icon, and bytes 4 types (2x in Message, and 2x in ConversationInput), and we have to pass this function down multiple layers. That's a good indicator that it can be extracted into a standalone component.

If there are slight variations in rendering depending on the context, those can be passed to the component as props.

2024-12-27 15:21 UTC, mattyg requested changes
This looks great! Just a few minor changes requested in comments.

Sorry I got some other PRs in yesterday so there are merge conflicts again. I'll be doing more today as well.

2024-12-27 15:28 UTC, MasterK0927 commented on ui/src/routes/conversations/[id]/+page.svelte
> +        <ConversationMessages messages={$processedMessages} {formatFileName} />
I was thinking for the same.

2024-12-27 15:30 UTC, MasterK0927 commented
> This looks great! Just a few minor changes requested in comments.
> 
> Sorry I got some other PRs in yesterday so there are merge conflicts again. I'll be doing more today as well.

Then in that case I will wait for that to be done first. Till then I am working on Voice Calls.

2024-12-29 16:27 UTC, MasterK0927 commented
- Resolves all the merge conflicts
- Migrates the thumbnail previews into a single component

2024-12-30 21:00 UTC, mattyg commented on ui/src/lib/Button.svelte
> +      <SvgIcon {icon} size={iconSize} color={$modeCurrent ? "white" : "%23FD3524"} />
As far as I can tell, the standard button should have a red icon in both light and dark modes -- that's how the figma mockups look. I'm assuming that's the intended styling and anything else we see in the code base is either a non-standard button, or is a mistake in the implementation. Lets revert this and keep the standard buttons with red icons.

2024-12-30 21:01 UTC, mattyg commented on ui/src/lib/FileIcon.svelte
:+1:

2024-12-30 21:05 UTC, mattyg commented on ui/src/lib/FilePreview.svelte
> +  export let onCancel: ((id: string) => void) | undefined = undefined;
Instead of passing functions from parent to child, please dispatch events from child to parent. This makes the flow of relationship between parent and child more clear and explicit. 

To accomplish this here you can do something like the following:

```
import { createEventDispatcher } from "svelte";
const dispatch = createEventDispatcher<{ cancel: string }>();
```

```
on:click={() => dispatch("cancel", file.id)
```


Then in the parent:
```
<FilePreview on:cancel={(e) => cancelUpload(e.detail)} />
```

2024-12-30 21:08 UTC, mattyg commented on ui/src/lib/FilePreview.svelte
> +  export let fromMe: boolean = false;
Rather than having props be specific to the context they are rendered within, lets make them as generic as possible so the component is as generally useful as possible, including in different contexts.

So in this case, lets change `fromMe: boolean = false` to `align: "left" | "right" = "left".

Or actually, even better lets avoid the magic strings by creating a an typescript enum in the `types.ts` file for `Alignment { Left, Right }` and then make the prop `align: Alignment = Alignment.Right`

2024-12-30 21:08 UTC, mattyg commented on ui/src/lib/FilePreview.svelte
> +  export let showCancel: boolean = false;
:+1:

2024-12-30 21:08 UTC, MasterK0927 commented on ui/src/lib/Button.svelte
> +      <SvgIcon {icon} size={iconSize} color={$modeCurrent ? "white" : "%23FD3524"} />
The button's background color is red by default, and the icon also turns red, causing it to blend in with the background.

So I did this

2024-12-30 21:09 UTC, mattyg commented on ui/src/lib/FilePreview.svelte
> +      {#if showCancel}
We should only need a single `{#if showCancel}` conditional that works for all cases.

2024-12-30 21:12 UTC, mattyg commented on ui/src/lib/FilePreview.svelte
> +{#if isMessage}
Lets avoid having props be specific to the parent's context. It seems like the `isMessage` prop is bundling several changes together:
- There is slightly different styling of the background
- There is different sizing of the icons and previews

We should be able to split these into multiple props that make the component more generic for use in different contexts. We may also potentially want to rendering the background in the parent component if that makes it easier.

2024-12-30 21:13 UTC, mattyg commented on ui/src/lib/FilePreview.svelte
> +  {#if file.status === "loading" || file.status === "pending"}
I see that the "pending" status is preventing us from rendering file previews in the the input field. I suggest we add another file status "preview" for this case.

2024-12-30 21:17 UTC, mattyg requested changes
Very good! Looking much better!

I requested some changes inline for making the `FilePreview` component more generic and avoid duplicating code. I pushed a few of the changes already and left the rest to you. Let me know if you have questions.

2024-12-30 21:19 UTC, mattyg commented on ui/src/lib/FilePreview.svelte
> +  export let onCancel: ((id: string) => void) | undefined = undefined;
(I made this change a pushed it - please take a look so its clear to you :))

2024-12-30 21:22 UTC, MasterK0927 commented on ui/src/lib/FilePreview.svelte
> +  export let onCancel: ((id: string) => void) | undefined = undefined;
I actually tried it, but was unable to get it working, so I chose to move with props. Although thanks, it will clear my confusion.

2024-12-30 21:22 UTC, mattyg commented on ui/src/lib/Button.svelte
> +      <SvgIcon {icon} size={iconSize} color={$modeCurrent ? "white" : "%23FD3524"} />
Ah it seems like we should change the default background of the Button component to match the styling used through the app, and remove the additional css classes used to override it in most of the places where it is used.

2024-12-30 21:26 UTC, mattyg commented on ui/src/lib/FilePreview.svelte
> +  export let fromMe: boolean = false;
(I made this change a pushed it - please take a look so its clear to you :))

2024-12-31 03:23 UTC, mattyg commented on ui/src/lib/Button.svelte
> +      <SvgIcon {icon} size={iconSize} color={$modeCurrent ? "white" : "%23FD3524"} />
For this PR lets leave it as is. I'm currently working through refactoring the button styling.

2024-12-31 08:52 UTC, MasterK0927 commented
Sorry to override your alignment related changes, but I think this is more generic to our use case.

2024-12-31 17:35 UTC, mattyg commented on ui/src/lib/FilePreview.svelte
> +  $: hasError = file.status === FileStatus.Error;
great!

2024-12-31 17:43 UTC, mattyg commented on ui/src/lib/types.ts
> +export enum Alignment {
If you're not using this type, please remove it.

2024-12-31 17:50 UTC, mattyg commented on ui/src/lib/types.ts
> +export enum Alignment {
I modified the implementation to use this type, to avoid "magic strings"

2024-12-31 17:56 UTC, MasterK0927 commented on ui/src/lib/types.ts
> +export enum Alignment {
Changing it to use Alignment enum was not working for me with my changes, please test it once.

2024-12-31 18:07 UTC, mattyg approved these changes
Nice! The FilePreview component looks great! So much simpler and clearer to quickly understand! Thanks for sticking with it.

I made a few minor changes and pushed them:
- using enum types for Alignment and Size, rather than magic string
- making a separate prop to enable the lightbox for images
- using css sflex-row and flex-row-reverse for alignment

I also pulled in the latest develop and resolved the merge conflicts. Next time please check if there are merge conflicts before requesting review :). If you see this message at the bottom of the PR page, then you know there are conflicts:
![image](https://github.com/user-attachments/assets/770487bd-cd5e-475b-83c4-e3e838ae1a9c)

2024-12-31 18:08 UTC, merged

2024-12-31 18:10 UTC, MasterK0927 commented
> Nice! The FilePreview component looks great! So much simpler and clearer to quickly understand! Thanks for sticking with it.
> 
> I made a few minor changes and pushed them:
> - using enum types for Alignment and Size, rather than magic string
> - making a separate prop to enable the lightbox for images
> - using css sflex-row and flex-row-reverse for alignment
> 
> I also pulled in the latest develop and resolved the merge conflicts. Next time please check if there are merge conflicts before requesting review :). If you see this message at the bottom of the PR page, then you know there are conflicts:
> ![image](https://github.com/user-attachments/assets/770487bd-cd5e-475b-83c4-e3e838ae1a9c)

Ahh I doubt I missed on your early morning commits. So merge conflicts emerged.